version: 0.1.15 ({build})

environment:
  PASSWORD:
    secure: KZdEfjKCVSUL334LJP/iPqWKfzhoIm43D4VZwJcEb0k=

  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python35
    - PYTHON: C:\Python36
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36-x64

init:
  - set VS90COMNTOOLS=%VS140COMNTOOLS%
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - git submodule update --init --recursive
  - choco install -y swig --allow-empty-checksums
  - python -m pip install --upgrade pip setuptools wheel twine

build: off

test_script:
  - python setup.py test

after_test:
  - python setup.py bdist_wheel
  - python setup.py bdist_wininst

artifacts:
  - path: dist/*

on_success:
  - if %APPVEYOR_REPO_TAG%==true twine upload -u bambucha -p %PASSWORD% dist/*
